In [1]:
!pip install pandas

# Data Preparation

In [2]:
#Functions:
#pandas.merge(): merging, connects the rows in a dataframe based on one or more keys.
#pandas.concat(): concatenating. Concatenates the objects along an axis.
#pandas.DataFrame.combine_first(): Combining. Methos that allows us to connect overlapped data in order to fill in missing values.
#                                  in a data structure by takking data from another structure.

import pandas as pd
import numpy as np

In [5]:
frame1 = pd.DataFrame({'id':['ball','pencil','pen','mug','ashtray'],
                      'price':[12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [10]:
frame2 = pd.DataFrame({'id':['pencil','pencil','ball','pen'],
                      'color': ['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [11]:
# Merging
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [12]:
#Key of merge
frame1 = pd.DataFrame({'id':['ball','pencil','pen','mug','ashtray'],
                      'color':['white','red','red','black','green'],
                      'brand':['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [13]:
frame2 = pd.DataFrame({'id':['pencil','pencil','ball','pen'],
                      'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [14]:
pd.merge(frame1,frame2, on = 'id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [15]:
pd.merge(frame1,frame2,on = 'brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [27]:
frame2.columns = ['brand','id']
frame2

brand   id
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [31]:
pd.merge(frame1,frame2, left_on = 'id', right_on = 'id')

Empty DataFrame
Columns: [id, color, brand_x, brand_y]
Index: []

In [28]:
# to select the type of the join, we must use how option
pd.merge(frame1,frame2,on = 'id', how = 'outer')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN
5      OMG    NaN     NaN  pencil
6      POD    NaN     NaN  pencil
7      POD    NaN     NaN     pen
8      ABC    NaN     NaN    ball

In [32]:
pd.merge(frame1,frame2,on = 'id',how = 'right')

id color brand_x brand_y
0  OMG   NaN     NaN  pencil
1  POD   NaN     NaN  pencil
2  POD   NaN     NaN     pen
3  ABC   NaN     NaN    ball

In [33]:
pd.merge(frame1,frame2,on = ['id','brand'], how = 'outer')

id  color   brand
0     ball  white     OMG
1   pencil    red     ABC
2      pen    red     ABC
3      mug  black     POD
4  ashtray  green     POD
5      OMG    NaN  pencil
6      POD    NaN  pencil
7      ABC    NaN    ball
8      POD    NaN     pen

# Concatenating

In [34]:
#concatenate()
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
np.concatenate([array1,array2], axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [38]:
np.concatenate([array1,array2], axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [40]:
 # concat(): pandas
ser1 = pd.Series(np.random.rand(4),index = [1,2,3,4])
ser1

1    0.531496
2    0.208131
3    0.561178
4    0.373659
dtype: float64

In [41]:
ser2 = pd.Series(np.random.rand(4), index = [5,6,7,8])
ser2

5    0.327957
6    0.820274
7    0.558707
8    0.718753
dtype: float64

In [43]:
pd.concat([ser1,ser2]) # by default the axis = 0

1    0.531496
2    0.208131
3    0.561178
4    0.373659
5    0.327957
6    0.820274
7    0.558707
8    0.718753
dtype: float64

In [44]:
pd.concat([ser1,ser2], axis = 1)

0         1
1  0.531496       NaN
2  0.208131       NaN
3  0.561178       NaN
4  0.373659       NaN
5       NaN  0.327957
6       NaN  0.820274
7       NaN  0.558707
8       NaN  0.718753

In [45]:
pd.concat([ser1,ser2], keys =[1,2])

1  1    0.531496
   2    0.208131
   3    0.561178
   4    0.373659
2  5    0.327957
   6    0.820274
   7    0.558707
   8    0.718753
dtype: float64

In [47]:
# with dataframes
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index = [1,2,3], columns = ['A','B','C'])
frame1

A         B         C
1  0.526713  0.079241  0.510589
2  0.278538  0.872537  0.069629
3  0.015528  0.182796  0.238366

In [49]:
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index = [4,5,6], columns = ['A','B','C'])
frame2

A         B         C
4  0.164379  0.672038  0.918967
5  0.309808  0.164613  0.794733
6  0.343022  0.700715  0.834274

In [52]:
pd.concat([frame1,frame2])

A         B         C
1  0.526713  0.079241  0.510589
2  0.278538  0.872537  0.069629
3  0.015528  0.182796  0.238366
4  0.164379  0.672038  0.918967
5  0.309808  0.164613  0.794733
6  0.343022  0.700715  0.834274

In [53]:
pd.concat([frame1,frame2], axis = 1)

A         B         C         A         B         C
1  0.526713  0.079241  0.510589       NaN       NaN       NaN
2  0.278538  0.872537  0.069629       NaN       NaN       NaN
3  0.015528  0.182796  0.238366       NaN       NaN       NaN
4       NaN       NaN       NaN  0.164379  0.672038  0.918967
5       NaN       NaN       NaN  0.309808  0.164613  0.794733
6       NaN       NaN       NaN  0.343022  0.700715  0.834274

# Combining

In [54]:
ser1 = pd.Series(np.random.rand(5), index = [1,2,3,4,5])
ser1

1    0.957298
2    0.036433
3    0.977418
4    0.491614
5    0.338571
dtype: float64

In [55]:
ser2 = pd.Series(np.random.rand(4), index = [2,4,5,6])
ser2

2    0.560847
4    0.233763
5    0.762786
6    0.237922
dtype: float64

In [56]:
ser1.combine_first(ser2)

1    0.957298
2    0.036433
3    0.977418
4    0.491614
5    0.338571
6    0.237922
dtype: float64

In [57]:
ser2.combine_first(ser1)

1    0.957298
2    0.560847
3    0.977418
4    0.233763
5    0.762786
6    0.237922
dtype: float64

In [58]:
ser1[:3].combine_first(ser2[:3])

1    0.957298
2    0.036433
3    0.977418
4    0.233763
5    0.762786
dtype: float64

# Pivoting

In [59]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),index = ['white','black','red'],columns = ['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [61]:
ser5 = frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [70]:
ser5.unstack(1)

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

# Pivoting from "Long" to "Wide" Format

In [72]:
longframe = pd.DataFrame({'color':['white','white','white','red','red','red','black','black','black'],
                         'item':['ball','pen','mug','ball','pen','mug','ball','pen','mug']})
longframe

color  item
0  white  ball
1  white   pen
2  white   mug
3    red  ball
4    red   pen
5    red   mug
6  black  ball
7  black   pen
8  black   mug

In [74]:
wideframe = longframe.pivot('color','item')
wideframe

Empty DataFrame
Columns: []
Index: [black, red, white]

# Removing

In [80]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                     index = ['white','black','red'],
                     columns = ['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [81]:
del frame1['ball'] #column

In [82]:
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [83]:
frame1.drop('white') #row

pen  pencil
black    4       5
red      7       8

# Data Transformation

# Removing duplicates

In [4]:
#dplicated(): return bolean values is this is TRUE, the row is duplicated
#drop_duplicates(): drop duplicates
dframe = pd.DataFrame({'color': ['white','white','red','red','white'],
                      'value': [2,1,3,3,2]})
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [5]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [6]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [7]:
dframe.drop_duplicates()

color  value
0  white      2
1  white      1
2    red      3

# Mapping

In [8]:
#replace(): Replaces values
#map(): Creates a new column
#rename(): Replace the index values

frame = pd.DataFrame({'item':['ball','mug','pen','pencil','ashtray'],
                     'color':['white','rosso','verde','black','yellow'],
                     'price':[5.56,4.20,1.30,0.56,2.75]})
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [11]:
#replacements.
newcolors = {
    'rosso': 'red',
    'verde':'green'
}

In [12]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [3]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [4]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

# Adding Values via Mapping

In [5]:
#function: map()
frame = pd.DataFrame({'item':['ball','mug','pen','pencil','ashtray'],
                     'color':['white','red','green','black','yellow']})
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [7]:
prices = {
    'ball':5.56,
    'mug':4.20,
    'bottle':1.30,
    'scissors':3.41,
    'pen':1.30,
    'pencil':0.56,
    'ashtray':2.75
}
frame['price'] = frame['item'].map(prices)
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [12]:
#Example 2
frame_subject = pd.DataFrame({'subject':['Investigacion Operativa','Mercadotecnia','Logística','Estadística','Finanzas','Derivados'],
                             'level':[7,8,8,6,8,10]})
frame_subject                             

subject  level
0  Investigacion Operativa      7
1            Mercadotecnia      8
2                Logística      8
3              Estadística      6
4                 Finanzas      8
5                Derivados     10

In [16]:
credits = {
    'Investigacion Operativa': 3.5,
    'Mercadotecnia': 3.5,
    'Logística': 3,
    'Estadística': 3,
    'Finanzas': 4,

}

Score = {
    'Investigacion Operativa': 14,
    'Mercadotecnia': 15,
    'Logística': 16,
    'Estadística': 17,
    'Finanzas': 15,

}



In [17]:
frame_subject['credits'] = frame_subject['subject'].map(credits)
frame_subject['score'] = frame_subject['subject'].map(Score)
frame_subject 

subject  level  credits  score
0  Investigacion Operativa      7      3.5   14.0
1            Mercadotecnia      8      3.5   15.0
2                Logística      8      3.0   16.0
3              Estadística      6      3.0   17.0
4                 Finanzas      8      4.0   15.0
5                Derivados     10      NaN    NaN

# Rename the Indexes of the Axes

In [18]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [25]:
reindex = {
    0: 'First',
    1: 'Second',
    2: 'Third',
    3: 'Fourth',
    4: 'Fifth',
    5: 'Sixth'
}
frame.rename(reindex)

item   color  price
First      ball   white   5.56
Second      mug     red   4.20
Third       pen   green   1.30
Fourth   pencil   black   0.56
Fifth   ashtray  yellow   2.75

In [22]:
#renamed the columns
recolumn = {
    'item':'Object',
    'price':'Value',
    'color':'Color'
}
frame.rename(index = reindex, columns = recolumn)


Object   Color  Value
First      ball   white   5.56
Second      mug     red   4.20
Third       pen   green   1.30
Fourth   pencil   black   0.56
Fifth   ashtray  yellow   2.75

In [26]:
#Example 2:
rename_columns = {
    'subject': 'Subject',
    'level': 'Level',
    'credits': 'Credits',
    'score': 'Score'
}

frame_subject.rename(index = reindex, columns = rename_columns)


Subject  Level  Credits  Score
First   Investigacion Operativa      7      3.5   14.0
Second            Mercadotecnia      8      3.5   15.0
Third                 Logística      8      3.0   16.0
Fourth              Estadística      6      3.0   17.0
Fifth                  Finanzas      8      4.0   15.0
Sixth                 Derivados     10      NaN    NaN

In [29]:
#If we have single vaue, ..
frame.rename(index = {1:'first'}, columns = {'item':'object'})

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

In [31]:
#inplace argument to save the changes:
frame.rename(columns = {'item':'Object'}, inplace = True)
frame

Object   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

# Discretization and Binning

In [33]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
results

[12, 34, 67, 55, 28, 90, 99, 12, 3, 56, 74, 44, 87, 23, 49, 89, 87]

In [35]:
bins = [0,25,50,75,100]
cat = pd.cut(results,bins)
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [36]:
pd.value_counts(cat)

(75, 100]    5
(50, 75]     4
(25, 50]     4
(0, 25]      4
dtype: int64

In [39]:
bin_names = ['unlikely','less likely','likely','highly likely']
category = pd.cut(results,bins, labels = bin_names)
category

['unlikely', 'less likely', 'likely', 'likely', 'less likely', ..., 'highly likely', 'unlikely', 'less likely', 'highly likely', 'highly likely']
Length: 17
Categories (4, object): ['unlikely' < 'less likely' < 'likely' < 'highly likely']

In [40]:
pd.value_counts(category)

highly likely    5
likely           4
less likely      4
unlikely         4
dtype: int64

# Detecting and Filtering outliers

In [43]:
# function describe(): statistics for each column.
randframe = pd.DataFrame(np.random.randn(1000,3))
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.027415    -0.021957     0.006358
std       0.990520     0.993799     1.052320
min      -3.572811    -3.113001    -3.349601
25%      -0.618396    -0.699751    -0.698230
50%       0.006163    -0.023403     0.007681
75%       0.640874     0.676326     0.731507
max       2.830491     3.347640     2.968857

In [44]:
# to see ony the standard deviation use std() function.
randframe.std()

0    0.990520
1    0.993799
2    1.052320
dtype: float64

In [47]:
#filtering values greater than three times standard deviation.
randframe[(np.abs(randframe)>(3*randframe.std())).any(1)]
# we use the any() method because thanks to it we can apply the filter on each column.

0         1         2
171 -3.572811  1.751467  0.330264
244 -3.338736 -0.597297 -0.171684
363  0.012904 -3.113001  1.455514
631  0.934923  3.347640 -0.573547
659  0.776060 -1.135410 -3.312699
734 -3.030691  1.772292  0.983568
762 -3.361873  0.182230 -0.256978
859  1.058175  3.167031  0.757593
943  1.210123 -2.759150 -3.349601

# Permutation

In [48]:
# function:np.random.permutation()
#function: take()
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [59]:
new_order = np.random.permutation(5)
new_order

array([1, 0, 2, 3, 4])

In [60]:
# now we're goint to apply this permutation to the dataframe by take() function.
nframe.take(new_order)

0   1   2   3   4
1   5   6   7   8   9
0   0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [61]:
# we can apply for other type of orders, for example:
new_order = [2,3,4,1,0]
nframe.take(new_order)

0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
1   5   6   7   8   9
0   0   1   2   3   4

# Random Sampling


In [68]:
#function: np.tandom.randint(): arguments(min, max, quantity)
sample = np.random.randint(0,len(nframe), size = 3)
sample

array([1, 1, 4])

In [70]:
nframe.take(sample)

0   1   2   3   4
1   5   6   7   8   9
1   5   6   7   8   9
4  20  21  22  23  24

# String Manipulation